baseURL = 'https://enterprise-contract.dev/'
languageCode = 'en-us'
title = 'Conforma'
theme = 'github.com/basil/antora-default-ui-hugo-theme'
publishDir = '../public'
copyright = 'Red Hat, Inc. All rights reserved. <a href="https://github.com/conforma/conforma.github.io">Source</a>.'
relativeURLs = true
staticDir = ["static", "antora"]
paginate = 12
# Added to enable embedding html lists in markdown tables.
[markup.goldmark.renderer]
unsafe = true
